### ISSUE TITLE
shelf

### ISSUE THREAD

**Issue by lipki** [SummerFields/Mod-Mintest-xDecor#12]
![xdecor_empty_shelf](https://cloud.githubusercontent.com/assets/401965/15862604/7c6c2de6-2cd0-11e6-887d-306f98598e2e.png)![xdecor_multishelf](https://cloud.githubusercontent.com/assets/401965/15862605/7c9956f4-2cd0-11e6-8284-8e400b7feb17.png)

**Comment by tobyplowy** [comment]
![xdecor_empty_shelf](https://cloud.githubusercontent.com/assets/16853304/15865167/02bc8dec-2cda-11e6-9f6a-071728a98822.png)
empty shelf done

**Comment by lipki** [comment]
![xdecor_empty_shelf png](https://cloud.githubusercontent.com/assets/401965/15873461/1940b05a-2cff-11e6-8bf0-4cf00836c1a3.png)
Without the edge ...

**Comment by lipki** [comment]
![xdecor_multishelf](https://cloud.githubusercontent.com/assets/401965/15874935/f94abfb4-2d05-11e6-9336-de81cf9edb49.png)

**Comment by lipki** [comment]
done
