### ISSUE TITLE
workbench

### ISSUE THREAD

**Issue by lipki** [SummerFields/Mod-Mintest-xDecor#15]
![xdecor_workbench_front](https://cloud.githubusercontent.com/assets/401965/15862701/c20f67c8-2cd0-11e6-812d-cc45d415817e.png)![xdecor_workbench_sides](https://cloud.githubusercontent.com/assets/401965/15862703/c230d034-2cd0-11e6-90d4-29b516e44ff3.png)![xdecor_workbench_top](https://cloud.githubusercontent.com/assets/401965/15862702/c22ecdac-2cd0-11e6-8234-16ab8a3c0cdf.png)

![xdecor_workbench_front](https://cloud.githubusercontent.com/assets/401965/15864121/0938a114-2cd6-11e6-9585-6ab2a20382ff.png)![xdecor_workbench_sides](https://cloud.githubusercontent.com/assets/401965/15864120/09388378-2cd6-11e6-9e54-f6c3054af539.png)![xdecor_workbench_top](https://cloud.githubusercontent.com/assets/401965/15864122/093eca12-2cd6-11e6-8534-ebf1406b49d4.png)

**Comment by lipki** [comment]
![xdecor_workbench_front](https://cloud.githubusercontent.com/assets/401965/15864121/0938a114-2cd6-11e6-9585-6ab2a20382ff.png)![xdecor_workbench_sides](https://cloud.githubusercontent.com/assets/401965/15864120/09388378-2cd6-11e6-9e54-f6c3054af539.png)![xdecor_workbench_top](https://cloud.githubusercontent.com/assets/401965/15864122/093eca12-2cd6-11e6-8534-ebf1406b49d4.png)

**Comment by lipki** [comment]
done ?

**Comment by tobyplowy** [comment]
yes this is done
