### ISSUE TITLE
Chess

### ISSUE THREAD

**Issue by lipki** [SummerFields/Mod-Mintest-xDecor#2]
![chessboard_top](https://cloud.githubusercontent.com/assets/401965/15861674/569d3dce-2ccd-11e6-9a3a-94c587d94607.png)![chessboard_top](https://cloud.githubusercontent.com/assets/401965/15756921/a7e018fa-2903-11e6-92f5-68d6e0e3e340.png)
![chessboard_sides](https://cloud.githubusercontent.com/assets/401965/15861445/b166b22c-2ccc-11e6-88ed-065652244595.png)

![pawn_black](https://cloud.githubusercontent.com/assets/401965/15758545/66e6e3e4-290b-11e6-9c50-7456d6bdb2b1.png)![rook_black](https://cloud.githubusercontent.com/assets/401965/15758553/69b21b70-290b-11e6-83e4-4de10270f82e.png)![knight_black](https://cloud.githubusercontent.com/assets/401965/15758542/64212c64-290b-11e6-803a-3f0f9f955eae.png)![bishop_black](https://cloud.githubusercontent.com/assets/401965/15758537/5f064c64-290b-11e6-8660-94c57c9085f2.png)![queen_black](https://cloud.githubusercontent.com/assets/401965/15758552/686ef418-290b-11e6-80bb-223846972f2f.png)![king_black](https://cloud.githubusercontent.com/assets/401965/15758540/620e6554-290b-11e6-87a4-d923ae0fa627.png)
![pawn_white](https://cloud.githubusercontent.com/assets/401965/15758802/7bbdfb44-290c-11e6-8e65-968143a4a0ba.png)![rook_white](https://cloud.githubusercontent.com/assets/401965/15758611/b862d37c-290b-11e6-872f-f84492003558.png)![knight_white](https://cloud.githubusercontent.com/assets/401965/15758680/ff84c418-290b-11e6-9e9f-272e66be6faf.png)![bishop_white](https://cloud.githubusercontent.com/assets/401965/15758631/c640163a-290b-11e6-9cf1-fc5d8b97ab13.png)![queen_white](https://cloud.githubusercontent.com/assets/401965/15758699/1260fe4e-290c-11e6-90f9-369b5ae6b6fb.png)![king_white](https://cloud.githubusercontent.com/assets/401965/15758624/bfc66336-290b-11e6-8735-088e650079f3.png)
![pawn_black](https://cloud.githubusercontent.com/assets/401965/15758778/646798f6-290c-11e6-8cdb-6a58b0b35699.png)![rook_black](https://cloud.githubusercontent.com/assets/401965/15758816/8aaddd18-290c-11e6-86bc-6e18657fea83.png)![knight_black](https://cloud.githubusercontent.com/assets/401965/15861155/fd050c98-2ccb-11e6-8c40-194483ccfa31.png)![bishop_black](https://cloud.githubusercontent.com/assets/401965/15758873/beba7ae4-290c-11e6-8c24-5d449a1afd6e.png)![queen_black](https://cloud.githubusercontent.com/assets/401965/15759717/44a72cd0-2910-11e6-8688-e44bbaf93c87.png)![king_black](https://cloud.githubusercontent.com/assets/401965/15760171/503fd770-2912-11e6-937f-0a2bc2d81151.png)
![pawn_white](https://cloud.githubusercontent.com/assets/401965/15758896/d7ef1876-290c-11e6-984d-3221a860aba4.png)![rook_white](https://cloud.githubusercontent.com/assets/401965/15758884/d43cbefe-290c-11e6-9e60-53f46128d423.png)![knight_white](https://cloud.githubusercontent.com/assets/401965/15861154/fd0204bc-2ccb-11e6-97e9-85fdeb4580e3.png)![bishop_white](https://cloud.githubusercontent.com/assets/401965/15758840/a290e696-290c-11e6-954f-e122623bb62b.png)![queen_white](https://cloud.githubusercontent.com/assets/401965/15759718/44ac1722-2910-11e6-9699-018130157738.png)![king_white](https://cloud.githubusercontent.com/assets/401965/15760172/506bffb2-2912-11e6-8deb-ffdb1b2c3063.png)

![chess_bg](https://cloud.githubusercontent.com/assets/401965/15861680/5dd38562-2ccd-11e6-9ce6-b9377c573fe2.png)![chess_bg](https://cloud.githubusercontent.com/assets/401965/15757247/f02975e2-2904-11e6-8b21-e076890f9d60.png)

**Comment by lipki** [comment]
i propose
![chess_bg](https://cloud.githubusercontent.com/assets/401965/15757247/f02975e2-2904-11e6-8b21-e076890f9d60.png)

**Comment by tobyplowy** [comment]
your chess board is better

**Comment by tobyplowy** [comment]
@lipki your chess board is better

**Comment by lipki** [comment]
you are not obliged to add @lipki I warned anyway.

**Comment by lipki** [comment]
![rook_black](https://cloud.githubusercontent.com/assets/401965/15757349/6c07bfc0-2905-11e6-85af-07af54aba73d.png)![rook_white](https://cloud.githubusercontent.com/assets/401965/15757350/6c10630a-2905-11e6-8352-667e1746b18c.png)

**Comment by tobyplowy** [comment]
so i can't mention your name?

**Comment by lipki** [comment]
yes exactly

**Comment by tobyplowy** [comment]
why?

**Comment by lipki** [comment]
When we participated in a conversation it is automatically notified of new.

**Comment by lipki** [comment]
yes, you can, but you do not have to.

**Comment by tobyplowy** [comment]
bud i can still do it on https://github.com/SummerFields/Minetest and https://github.com/SummerFields/SummerFields

**Comment by lipki** [comment]
it's the same everywhere, I will always be warned, if I already participate in the conversation.
(And I'm the big boss :) I receive an email for each event here)

**Comment by lipki** [comment]
![pawn_black](https://cloud.githubusercontent.com/assets/401965/15757737/5d19dd34-2907-11e6-880c-1e4624098e80.png)![pawn_white](https://cloud.githubusercontent.com/assets/401965/15757738/5d1a839c-2907-11e6-8982-38ec22401577.png)

**Comment by tobyplowy** [comment]
(And I'm the big boss :) lol

**Comment by lipki** [comment]
![rook_black](https://cloud.githubusercontent.com/assets/401965/15758428/defab582-290a-11e6-9277-a5968cb81e44.png)![rook_white](https://cloud.githubusercontent.com/assets/401965/15758429/df02cc2c-290a-11e6-9e8c-1b9791b408c2.png)

**Comment by lipki** [comment]
![queen_black](https://cloud.githubusercontent.com/assets/401965/15759708/397e97a8-2910-11e6-99b6-67dc9893b334.png)![queen_white](https://cloud.githubusercontent.com/assets/401965/15759709/39821446-2910-11e6-8283-2b4769cf5879.png)
![king_black](https://cloud.githubusercontent.com/assets/401965/15760203/678e5460-2912-11e6-897c-069da071464f.png)![king_white](https://cloud.githubusercontent.com/assets/401965/15760205/67927d6a-2912-11e6-96ec-1ed2a8b12001.png)

**Comment by tobyplowy** [comment]
Nice work

**Comment by tobyplowy** [comment]
chessboard_sides.png done
![chessboard_sides](https://cloud.githubusercontent.com/assets/16853304/15788203/9e9e68c8-29c6-11e6-9747-3500ddaf9230.png)

**Comment by tobyplowy** [comment]
now just the knight and Chess is done and can be losed

**Comment by tobyplowy** [comment]
Is the knight already done?

**Comment by lipki** [comment]
not yet !

**Comment by tobyplowy** [comment]
Hey lipki I am working on a little (Big!) project but I can't really promise anything ([I'm retexturing this game](http://pixbits.com)) also I'm working on some other stuff so I won't be able to do anything at the time but I will come back for sure, also is there any known date the customizer is going to work? And will it support Minetest

**Comment by lipki** [comment]
I remember playing with a minecraft texture pack inspired by junkjack :)

Yes the "Customizer" will be compatible Minetest.
(It's even Minetest I start doing it)

**Comment by tobyplowy** [comment]
Did you try to say (It's even because of Minetest I started doing it) 

If so, really I thought you didn't play mind test XD

(I can't promise anything about Junk Jack)

Also I will not be able to do much textures for summerfields (but I will be back in the vacation)

**Comment by lipki** [comment]
I remember playing with a minecraft texture pack inspired by junkjack :)

Yes the "Customizer" will be compatible Minetest.
(It's even Minetest I start doing it)

**Comment by lipki** [comment]
![knight_white](https://cloud.githubusercontent.com/assets/401965/15861154/fd0204bc-2ccb-11e6-97e9-85fdeb4580e3.png)
![knight_black](https://cloud.githubusercontent.com/assets/401965/15861155/fd050c98-2ccb-11e6-8c40-194483ccfa31.png)

**Comment by lipki** [comment]
bon ba done !
if you wan't

**Comment by tobyplowy** [comment]
Nice, I can't make chess pieces I really lack the skill :(
