### ISSUE TITLE
pot

### ISSUE THREAD

**Issue by lipki** [SummerFields/Mod-Mintest-xDecor#24]
![xdecor_dandelion_white_pot](https://cloud.githubusercontent.com/assets/401965/15863165/43a62e38-2cd2-11e6-92ec-fa9c1cf1b01d.png)![xdecor_dandelion_yellow_pot](https://cloud.githubusercontent.com/assets/401965/15863164/43a48bd2-2cd2-11e6-826d-dd3436ece8b0.png)![xdecor_geranium_pot](https://cloud.githubusercontent.com/assets/401965/15863167/43a8ef92-2cd2-11e6-9ab6-5024c015d0bc.png)![xdecor_rose_pot](https://cloud.githubusercontent.com/assets/401965/15863166/43a89470-2cd2-11e6-9531-2d98bec98381.png)![xdecor_tulip_pot](https://cloud.githubusercontent.com/assets/401965/15863168/43ae552c-2cd2-11e6-9d8b-854dd5f49c40.png)![xdecor_viola_pot](https://cloud.githubusercontent.com/assets/401965/15863169/43b1b0fa-2cd2-11e6-8990-308f29628169.png)

**Comment by lipki** [comment]
![xdecor_dandelion_white_pot](https://cloud.githubusercontent.com/assets/401965/15878440/485df85e-2d1b-11e6-9cbe-04e675b3a0a3.png)![xdecor_dandelion_yellow_pot](https://cloud.githubusercontent.com/assets/401965/15878443/4889adf0-2d1b-11e6-9e06-5b9786a781bb.png)![xdecor_geranium_pot](https://cloud.githubusercontent.com/assets/401965/15878441/4886d670-2d1b-11e6-8a19-5ca7062fc0e7.png)![xdecor_rose_pot](https://cloud.githubusercontent.com/assets/401965/15878442/48895f1c-2d1b-11e6-9f00-5ca5124404d0.png)![xdecor_tulip_pot](https://cloud.githubusercontent.com/assets/401965/15878444/488bd328-2d1b-11e6-9d2f-92a71b30d902.png)![xdecor_viola_pot](https://cloud.githubusercontent.com/assets/401965/15878445/488ffe62-2d1b-11e6-9397-5a631bd9147d.png)

**Comment by lipki** [comment]
done ?

**Comment by tobyplowy** [comment]
I guess this is done
