### ISSUE TITLE
xdecor crafting guide

### ISSUE THREAD

**Issue by lipki** [SummerFields/Mod-Mintest-xDecor#4]
![xdecor_crafting_guide](https://cloud.githubusercontent.com/assets/401965/15760834/6c406482-2915-11e6-9c8e-04588cd4c112.png)
![xdecor_crafting_guide](https://cloud.githubusercontent.com/assets/16853304/15787980/769d4264-29c5-11e6-9437-ea8182575d07.png)

**Comment by lipki** [comment]
![xdecor_book_open](https://cloud.githubusercontent.com/assets/401965/15862214/3e7de35e-2ccf-11e6-82bb-258c570ed3e0.png)![xdecor_crafting_guide](https://cloud.githubusercontent.com/assets/401965/15760742/e7889dd6-2914-11e6-8f1e-df5706cbbc28.png)

**Comment by tobyplowy** [comment]
i made this  
![xdecor_crafting_guide](https://cloud.githubusercontent.com/assets/16853304/15787680/e13a2b02-29c3-11e6-81d3-20e60f548ebc.png)
i also made a variation 
![xdecor_crafting_guide](https://cloud.githubusercontent.com/assets/16853304/15787980/769d4264-29c5-11e6-9437-ea8182575d07.png)

**Comment by lipki** [comment]
ok for your second.
