### ISSUE TITLE
frames/windows

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Mod-Mintest-xDecor#5]
![xdecor_bamboo_frame](https://cloud.githubusercontent.com/assets/401965/15861519/e4f8c602-2ccc-11e6-9e64-5d3f5fe7ff8e.png)![xdecor_itemframe](https://cloud.githubusercontent.com/assets/401965/15861520/e4fc086c-2ccc-11e6-803c-0be2c88695e5.png)![xdecor_wood_frame](https://cloud.githubusercontent.com/assets/401965/15861599/1763b016-2ccd-11e6-83e9-cb3f75b54401.png)![xdecor_woodframed_glass](https://cloud.githubusercontent.com/assets/401965/15861522/e5036d3c-2ccc-11e6-8427-69c5a7163b09.png)![xdecor_woodframed_glass_detail](https://cloud.githubusercontent.com/assets/401965/15861523/e505cd5c-2ccc-11e6-8611-f021ef07fd28.png)

![xdecor_bamboo_frame](https://cloud.githubusercontent.com/assets/16853304/15787562/5eed9b16-29c3-11e6-8f80-2f759f184502.png)![xdecor_itemframe](https://cloud.githubusercontent.com/assets/401965/15863698/590c4a58-2cd4-11e6-9b22-cbbe6530a3e6.png)![xdecor_wood_frame](https://cloud.githubusercontent.com/assets/401965/15861521/e5017432-2ccc-11e6-896f-a8c254e35645.png)![xdecor_woodframed_glass](https://cloud.githubusercontent.com/assets/401965/15863991/7d8784c8-2cd5-11e6-8aab-7aaa817c5c3a.png)![xdecor_woodframed_glass_detail](https://cloud.githubusercontent.com/assets/401965/15863992/7db86d90-2cd5-11e6-8959-9832c9010ba8.png).

**Comment by tobyplowy** [comment]
xdecor_bamboo_frame.png done
![xdecor_bamboo_frame](https://cloud.githubusercontent.com/assets/16853304/15787562/5eed9b16-29c3-11e6-8f80-2f759f184502.png)

**Comment by lipki** [comment]
very nice.

**Comment by tobyplowy** [comment]
Thanks :D

**Comment by lipki** [comment]
![xdecor_itemframe](https://cloud.githubusercontent.com/assets/401965/15863986/7a6f6d3c-2cd5-11e6-84e3-5c4a6e1e63bc.png)![xdecor_woodframed_glass](https://cloud.githubusercontent.com/assets/401965/15863991/7d8784c8-2cd5-11e6-8aab-7aaa817c5c3a.png)![xdecor_woodframed_glass_detail](https://cloud.githubusercontent.com/assets/401965/15863992/7db86d90-2cd5-11e6-8959-9832c9010ba8.png).

**Comment by lipki** [comment]
done ?

**Comment by tobyplowy** [comment]
nice textures (yes I think this issue is done)
