### ISSUE TITLE
cactus

### ISSUE THREAD

**Issue by lipki** [SummerFields/Mod-Mintest-xDecor#8]
![xdecor_cactusbrick](https://cloud.githubusercontent.com/assets/401965/15862451/ff958cc2-2ccf-11e6-84dd-11df3932a106.png)

**Comment by lipki** [comment]
by @tobyplowy 
![xdecor_cactusbrick](https://cloud.githubusercontent.com/assets/401965/15862457/05514fb6-2cd0-11e6-8745-17c4d5307d41.png)

**Comment by lipki** [comment]
done

**Comment by tobyplowy** [comment]
Keep your texture as a variation for the customizer
