### ISSUE TITLE
enchantment table

### ISSUE THREAD

**Issue by lipki** [SummerFields/Mod-Mintest-xDecor#9]
![xdecor_enchantment_bottom](https://cloud.githubusercontent.com/assets/401965/15862546/46d5177e-2cd0-11e6-9ed1-5fcd50968afc.png)![xdecor_enchantment_side](https://cloud.githubusercontent.com/assets/401965/15862548/4708c0ce-2cd0-11e6-8430-f4612e550ac2.png)![xdecor_enchantment_top](https://cloud.githubusercontent.com/assets/401965/15862547/47081b4c-2cd0-11e6-8f5f-7753d4aec804.png)![xdecor_book_open](https://cloud.githubusercontent.com/assets/401965/15872451/cb7ad666-2cf9-11e6-9774-5e2ea854d4da.png)

![xdecor_enchantment_bottom](https://cloud.githubusercontent.com/assets/16853304/15864901/110a34f4-2cd9-11e6-9606-686ed2cdd812.png)![xdecor_enchantment_side](https://cloud.githubusercontent.com/assets/16853304/15864896/0a790df4-2cd9-11e6-9465-18e5e129e374.png)![xdecor_enchantment_top](https://cloud.githubusercontent.com/assets/16853304/15864899/0cdf98f6-2cd9-11e6-8a6c-413ccce99176.png)![xdecor_book_open](https://cloud.githubusercontent.com/assets/401965/15873291/47db1c4e-2cfe-11e6-9ff4-de3dd3fa4677.png)

![xdecor_glyph1](https://cloud.githubusercontent.com/assets/401965/15862619/8e1611d8-2cd0-11e6-936f-621dd6458f71.png)![xdecor_glyph2](https://cloud.githubusercontent.com/assets/401965/15862624/8e4957aa-2cd0-11e6-8190-946a89ba08cb.png)![xdecor_glyph3](https://cloud.githubusercontent.com/assets/401965/15862621/8e4548a4-2cd0-11e6-8de9-9cfc98dc8146.png)![xdecor_glyph4](https://cloud.githubusercontent.com/assets/401965/15862622/8e470996-2cd0-11e6-97f6-b0748ffd2480.png)![xdecor_glyph5](https://cloud.githubusercontent.com/assets/401965/15862623/8e47d45c-2cd0-11e6-9477-714a804484d6.png)![xdecor_glyph6](https://cloud.githubusercontent.com/assets/401965/15862625/8e4a9e80-2cd0-11e6-91e8-ab9ba298a9b3.png)![xdecor_glyph7](https://cloud.githubusercontent.com/assets/401965/15862620/8e367e6e-2cd0-11e6-8c1d-25e5f6a7012e.png)![xdecor_glyph8](https://cloud.githubusercontent.com/assets/401965/15862626/8e56cea8-2cd0-11e6-954d-1cf5df087bec.png)![xdecor_glyph9](https://cloud.githubusercontent.com/assets/401965/15862627/8e5fc1de-2cd0-11e6-9d88-1f99044e6591.png)![xdecor_glyph10](https://cloud.githubusercontent.com/assets/401965/15862628/8e633de6-2cd0-11e6-8425-dcfd9cafafa4.png)![xdecor_glyph11](https://cloud.githubusercontent.com/assets/401965/15862632/8e7a4108-2cd0-11e6-9c38-d28b54288d95.png)![xdecor_glyph12](https://cloud.githubusercontent.com/assets/401965/15862629/8e6a9898-2cd0-11e6-931b-e950d5e0ad85.png)![xdecor_glyph13](https://cloud.githubusercontent.com/assets/401965/15862631/8e7a1d86-2cd0-11e6-9b47-39029ddc3360.png)![xdecor_glyph14](https://cloud.githubusercontent.com/assets/401965/15862630/8e74d326-2cd0-11e6-808d-a0530678d822.png)![xdecor_glyph15](https://cloud.githubusercontent.com/assets/401965/15862633/8e7f7a60-2cd0-11e6-9447-cd71dc4aa848.png)![xdecor_glyph16](https://cloud.githubusercontent.com/assets/401965/15862634/8e815e8e-2cd0-11e6-8078-84f32e83c000.png)![xdecor_glyph17](https://cloud.githubusercontent.com/assets/401965/15862635/8e89a116-2cd0-11e6-8f2e-8e4db079b1c3.png)![xdecor_glyph18](https://cloud.githubusercontent.com/assets/401965/15862636/8e907fae-2cd0-11e6-855a-63c89e1816a4.png)

![xdecor_glyph1](https://cloud.githubusercontent.com/assets/401965/15869827/5c584e2c-2cee-11e6-8d44-c064b1655f1d.png)![xdecor_glyph2](https://cloud.githubusercontent.com/assets/401965/15869828/5c5b46b8-2cee-11e6-9107-48c072015e16.png)![xdecor_glyph3](https://cloud.githubusercontent.com/assets/401965/15869829/5c5f7a94-2cee-11e6-9603-081cba4c607e.png)![xdecor_glyph4](https://cloud.githubusercontent.com/assets/401965/15869831/5c671fe2-2cee-11e6-8acc-cc9ff9c61b9e.png)![xdecor_glyph5](https://cloud.githubusercontent.com/assets/401965/15869830/5c6245da-2cee-11e6-858d-adc7a734d278.png)![xdecor_glyph6](https://cloud.githubusercontent.com/assets/401965/15869832/5c67a20a-2cee-11e6-87e0-6cfb343b6763.png)![xdecor_glyph7](https://cloud.githubusercontent.com/assets/401965/15869833/5c71ecec-2cee-11e6-9610-a2680693434c.png)![xdecor_glyph8](https://cloud.githubusercontent.com/assets/401965/15869834/5c76bae2-2cee-11e6-8eb2-3dc2d041465a.png)![xdecor_glyph9](https://cloud.githubusercontent.com/assets/401965/15869838/5c885c98-2cee-11e6-82f0-d452f2511e7e.png)![xdecor_glyph10](https://cloud.githubusercontent.com/assets/401965/15869835/5c7c612c-2cee-11e6-84e2-adec79e923e5.png)![xdecor_glyph11](https://cloud.githubusercontent.com/assets/401965/15869837/5c851ae2-2cee-11e6-9a31-61d0078eb5dd.png)![xdecor_glyph12](https://cloud.githubusercontent.com/assets/401965/15869836/5c832804-2cee-11e6-939c-4441988c3f13.png)![xdecor_glyph13](https://cloud.githubusercontent.com/assets/401965/15869839/5c8af066-2cee-11e6-8f14-cfe9d57e8e70.png)![xdecor_glyph14](https://cloud.githubusercontent.com/assets/401965/15869840/5c927278-2cee-11e6-8021-280699f2f7e9.png)![xdecor_glyph15](https://cloud.githubusercontent.com/assets/401965/15869841/5c94f8f4-2cee-11e6-9d37-fa41e1a8770f.png)![xdecor_glyph16](https://cloud.githubusercontent.com/assets/401965/15869842/5c9bff78-2cee-11e6-8289-46d250824373.png)![xdecor_glyph17](https://cloud.githubusercontent.com/assets/401965/15869844/5ca57c6a-2cee-11e6-85a2-328e6f83f1b6.png)![xdecor_glyph18](https://cloud.githubusercontent.com/assets/401965/15869843/5ca2d35c-2cee-11e6-810a-9c3faabed991.png)

![ench_ui](https://cloud.githubusercontent.com/assets/401965/15863335/e8273768-2cd2-11e6-82b9-e103139b7f91.png)
![ench_ui](https://cloud.githubusercontent.com/assets/401965/15873300/52c6af88-2cfe-11e6-90d2-9a02ab12fda5.png)

![bg_btn](https://cloud.githubusercontent.com/assets/401965/15863376/0ade4fb2-2cd3-11e6-82c7-7446a1802f09.png)![bg_btn](https://cloud.githubusercontent.com/assets/401965/15878597/86b6a320-2d1c-11e6-8e47-e4c88d1ce4b0.png)

**Comment by tobyplowy** [comment]
These are the textures from the base texture pack apart from the side one that's one i had to edit.
![xdecor_enchantment_side](https://cloud.githubusercontent.com/assets/16853304/15864896/0a790df4-2cd9-11e6-9465-18e5e129e374.png)
![xdecor_enchantment_top](https://cloud.githubusercontent.com/assets/16853304/15864899/0cdf98f6-2cd9-11e6-8a6c-413ccce99176.png)
![xdecor_enchantment_bottom](https://cloud.githubusercontent.com/assets/16853304/15864901/110a34f4-2cd9-11e6-9606-686ed2cdd812.png)

**Comment by lipki** [comment]
![xdecor_glyph1](https://cloud.githubusercontent.com/assets/401965/15869827/5c584e2c-2cee-11e6-8d44-c064b1655f1d.png)![xdecor_glyph2](https://cloud.githubusercontent.com/assets/401965/15869828/5c5b46b8-2cee-11e6-9107-48c072015e16.png)![xdecor_glyph3](https://cloud.githubusercontent.com/assets/401965/15869829/5c5f7a94-2cee-11e6-9603-081cba4c607e.png)![xdecor_glyph4](https://cloud.githubusercontent.com/assets/401965/15869831/5c671fe2-2cee-11e6-8acc-cc9ff9c61b9e.png)![xdecor_glyph5](https://cloud.githubusercontent.com/assets/401965/15869830/5c6245da-2cee-11e6-858d-adc7a734d278.png)![xdecor_glyph6](https://cloud.githubusercontent.com/assets/401965/15869832/5c67a20a-2cee-11e6-87e0-6cfb343b6763.png)![xdecor_glyph7](https://cloud.githubusercontent.com/assets/401965/15869833/5c71ecec-2cee-11e6-9610-a2680693434c.png)![xdecor_glyph8](https://cloud.githubusercontent.com/assets/401965/15869834/5c76bae2-2cee-11e6-8eb2-3dc2d041465a.png)![xdecor_glyph9](https://cloud.githubusercontent.com/assets/401965/15869838/5c885c98-2cee-11e6-82f0-d452f2511e7e.png)![xdecor_glyph10](https://cloud.githubusercontent.com/assets/401965/15869835/5c7c612c-2cee-11e6-84e2-adec79e923e5.png)![xdecor_glyph11](https://cloud.githubusercontent.com/assets/401965/15869837/5c851ae2-2cee-11e6-9a31-61d0078eb5dd.png)![xdecor_glyph12](https://cloud.githubusercontent.com/assets/401965/15869836/5c832804-2cee-11e6-939c-4441988c3f13.png)![xdecor_glyph13](https://cloud.githubusercontent.com/assets/401965/15869839/5c8af066-2cee-11e6-8f14-cfe9d57e8e70.png)![xdecor_glyph14](https://cloud.githubusercontent.com/assets/401965/15869840/5c927278-2cee-11e6-8021-280699f2f7e9.png)![xdecor_glyph15](https://cloud.githubusercontent.com/assets/401965/15869841/5c94f8f4-2cee-11e6-9d37-fa41e1a8770f.png)![xdecor_glyph16](https://cloud.githubusercontent.com/assets/401965/15869842/5c9bff78-2cee-11e6-8289-46d250824373.png)![xdecor_glyph17](https://cloud.githubusercontent.com/assets/401965/15869844/5ca57c6a-2cee-11e6-85a2-328e6f83f1b6.png)![xdecor_glyph18](https://cloud.githubusercontent.com/assets/401965/15869843/5ca2d35c-2cee-11e6-810a-9c3faabed991.png)

**Comment by lipki** [comment]
![ench_ui](https://cloud.githubusercontent.com/assets/401965/15872322/1890d168-2cf9-11e6-9afb-e49f14d0a5e4.png)

**Comment by lipki** [comment]
done ?

**Comment by tobyplowy** [comment]
I guess this topic is done

**Comment by lipki** [comment]
nop I remake the open book.

**Comment by tobyplowy** [comment]
Well once that's done you can actually close this topic :D

**Comment by lipki** [comment]
![xdecor_book_open](https://cloud.githubusercontent.com/assets/401965/15873291/47db1c4e-2cfe-11e6-9ff4-de3dd3fa4677.png)
![ench_ui](https://cloud.githubusercontent.com/assets/401965/15873300/52c6af88-2cfe-11e6-90d2-9a02ab12fda5.png)

you can close too

**Comment by tobyplowy** [comment]
Nice book :)
